# Site settings
baseURL = "/"
languageCode = "en-US"
title = "Learning from Language Workshop"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2020 Gary Lupyan"

[params]

  # Metadata for search engines and social sharing
  name = ""
  description = "Learning from Language Workshop. UW2020"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Content
  # Link syntax:[ipsum in](#)
  [params.content]
    name = ""
    tagline = "Learning from Language"
    bio = """

Animals learn from perceiving and navigating through their natural environment. But as humans we benefit from a source of knowledge unavailable to other animals: language. The goal of this workshop is to discuss some ways in which our knowledge is informed by our experience with language. Some questions the speakers will be tackling are:


a) How much “work” is language doing in children’s cognitive development, and vice versa?


b) What do recent successes in natural language processing (e.g., word embeddings, predictive language models) tell us about the kind of information that is and is not embedded in language?


c)  What is the relationship between vocabulary and working memory? To what extent might vocabulary form the “units” over which working memory operates?


d) Does perceptual information embedded in the distributional structure of language affect people’s knowledge of what things look like/sound like/feel like, etc.?


e) Do cross-linguistic differences in vocabulary mean that people learning different languages come to have different perceptual/conceptual categories? What evidence speaks for and against this idea?


f) Are there meaningful individual differences between people’s use of/reliance on natural language in memory/thinking/reasoning/learning?


g) How can embodiment (being able to perceive and interact physically with our environment) affect the learning and representation of language in humans and artificial neural networks.


h) What would a model that can effectively link language with other forms of experience be like, so that language can inform our understanding of the world and the world can inform our understanding of language?

"""

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      files = ["images/background.jpg"]
      position = "center center"
      #timer = 10000 # ms

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Speaker"

      [[params.links.list1.link]]
        text = "Ben Pitt (UC Berkeley)"
        url = "https://casasanto.com/benjaminpitt/"

      [[params.links.list1.link]]
        text = "Idan Blank/Ev Fedorenko (MIT)"
        url = "https://evlab.mit.edu/"

      [[params.links.list1.link]]
        text = "Judy Kim (Yale)"
        url = "https://www.judyseinkim.com/"

      [[params.links.list1.link]]
        text = "Gary Lupyan (UW-Madison)"
        url = "http://http://sapir.psych.wisc.edu/"

      [[params.links.list1.link]]
        text = "Rob Goldstone (Indiana)"
        url = "https://pc.cogs.indiana.edu/"

      [[params.links.list1.link]]
        text = "Barbara Malt (Lehigh)"
        url = "https://www.lehigh.edu/~bcm0/bcm0/index.html"

      [[params.links.list1.link]]
        text = "Vladimir Sloutsky (Ohio State)"
        url = "https://u.osu.edu/cogdevlab/"

      [[params.links.list1.link]]
        text = "Elika Bergelson (Duke)"
        url = "https://bergelsonlab.com/"

      [[params.links.list1.link]]
        text = "Haley Vlach (UW-Madison)"
        url = "https://vlachlab.education.wisc.edu/"

      [[params.links.list1.link]]
        text = "Dedre Gentner (Northwestern)"
        url = "https://groups.psych.northwestern.edu/gentner/coglanglab.htm"

      [[params.links.list1.link]]
        text = "Felix Hill (DeepMind)"
        url = "https://fh295.github.io/"

      [[params.links.list1.link]]
        text = "Jay McClelland (Stanford)"
        url = "https://stanford.edu/~jlmcc/"


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Title"

      [[params.links.list2.link2]]
        text = "Exact number concepts depend on language: Evidence from the Tsimane’"
        url = "#"
        icon = "youtube"

      [[params.links.list2.link2]]
        text = "Language and thought in the mind and brain"
        url = "#"
        icon = "youtube"

      [[params.links.list2.link2]]
        text = "The role of language in how blind individuals learn about the “visual” world"
        url = "#"
        icon = "youtube"


      [[params.links.list2.link2]]
        text = "Carving nature at its joints and carving joints into nature"
        url = "#"
        icon = "youtube"

      [[params.links.list2.link2]]
        text = "Changes of perceptual encodings due to labeling"
        url = "#"
        icon = "youtube"

      [[params.links.list2.link2]]
        text = "Are We Asking the Right Question?"
        url = "#"
        icon = "youtube"

      [[params.links.list2.link2]]
        text = "Language structure and semantic development"
        url = "#"
        icon = "youtube"

      [[params.links.list2.link2]]
        text = "Linking input, output, and uptake in early language development"
        url = "#"
        icon = "youtube"

      [[params.links.list2.link2]]
        text = "Beyond size: Word meanings underlying early word production"
        url = "#"
        icon = "youtube"


      [[params.links.list2.link2]]
        text = "The roles of language in learning and reasoning"
        url = "#"
        icon = "youtube"

      [[params.links.list2.link2]]
        text = "Embodied agent-based models of language learning"
        url = "#"
        icon = "youtube"


      [[params.links.list2.link2]]
        text = "An AI and Cognitive Neuroscience Inspired Integrated Understanding System"
        url = "#"
        icon = "youtube"


  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
